apiVersion: kubespiffe.io/v1alpha1
kind: WorkloadRegistration
metadata:
  name: workload
spec:
  spiffeID: spiffe://example.org/ns/default/sa/workload-sa
  svidType: X509
  selector:
    namespace: default
    serviceAccountName: workload-sa
---
apiVersion: kubespiffe.io/v1alpha1
kind: WorkloadRegistration
metadata:
  name: another-workload
spec:
  spiffeID: spiffe://example.org/app/another-workload
  svidType: X509
  selector:
    namespace: default
    serviceAccountName: another-workload-sa
