//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
The kubespiffe Authors 2025
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRegistration) DeepCopyInto(out *WorkloadRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRegistration.
func (in *WorkloadRegistration) DeepCopy() *WorkloadRegistration {
	if in == nil {
		return nil
	}
	out := new(WorkloadRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRegistrationList) DeepCopyInto(out *WorkloadRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRegistrationList.
func (in *WorkloadRegistrationList) DeepCopy() *WorkloadRegistrationList {
	if in == nil {
		return nil
	}
	out := new(WorkloadRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRegistrationSpec) DeepCopyInto(out *WorkloadRegistrationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRegistrationSpec.
func (in *WorkloadRegistrationSpec) DeepCopy() *WorkloadRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRegistrationStatus) DeepCopyInto(out *WorkloadRegistrationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRegistrationStatus.
func (in *WorkloadRegistrationStatus) DeepCopy() *WorkloadRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}
